library(ggplot2)
data("Orange")
Org.mod = lm(circumference~age,data=Orange)
pdf("Result.pdf")
plot(Orange[,-1])+abline(Org.mod)
ggplot(Orange)+geom_point(aes(y=circumference,x=age,color=3))
ggplot(Orange)+geom_point(aes(y=circumference,x=age,color=3))+geom_abline(intercept = coef(Org.mod)[1],slope = coef(Org.mod)[2])
ggplot(Orange,)+geom_point(aes(x=age,y=circumference))+ geom_smooth(mapping = aes(x=age,y=circumference),method = "lm",se=FALSE)
dev.off()